# Generated by Django 3.2.9 on 2022-05-13 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20220513_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goodies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('sold', models.BooleanField(default=False)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2022)])),
                ('type', models.CharField(choices=[('Disques/Enregistrements', 'Records'), ('Vêtements', 'Clothing'), ('Affiches', 'Posters'), ('Divers', 'Miscellaneous')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Disc',
        ),
        migrations.AlterField(
            model_name='band',
            name='year_formed',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
