# Generated by Django 3.2.9 on 2022-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_alter_goodies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodies',
            name='description',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
    ]
